version: "3.8"

services:
  langinfra:
    image: langinfra/langinfra:1.0-alpha
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGINFRA_DATABASE_URL=postgresql://langinfra:langinfra@postgres:5432/langinfra
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - LANGINFRA_CONFIG_DIR=app/langinfra
    volumes:
      - langinfra-data:/app/langinfra

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langinfra
      POSTGRES_PASSWORD: langinfra
      POSTGRES_DB: langinfra
    ports:
      - "5432:5432"
    volumes:
      - langinfra-postgres:/var/lib/postgresql/data

volumes:
  langinfra-postgres:
  langinfra-data:
